### DISCUSSION TITLE
Schedule runs in Portainer

### DISCUSSION THREAD

**Discussion by OddSquirrel** [vogler/free-games-claimer#110] [Q&A]
Hi guys,

So, I just found this masterpiece, and it's running beautifully. Now, I'm quite reta... uhmm... let's say containerizationally-challenged.
I do run a few services via Portainer, which works great without me breaking either my fingers or the Internet, so there's that.

Unfortunately, being a mere script kiddie has its flaws. Since that container isn't running continuously and executing defined runs, but rather executing the whole nine yards once it's executed, I'm in a bit of a bind.

The problem is: How would I schedule those runs? Yes, running docker by itself would probably call for `cron`. But I'm using Portainer for the safety of myself and others. And, for whatever reason, there isn't a simple setting available that allows for a schedule. Beats me.

Does anybody else have an idea how I could go about daily restarts that doesn't involve going back to college for several years? 🤔

**Comment by z4ch523** [comment]
I had the same problem and I guess it would be great if the container had an option to tell it a schedule. Maybe this could be a feature to enter the cron job as an variable?

In the meantime:
Fortunately my host OS (unraid) allows to have scripts run as cron jobs. What OS are you using?

In general - To start a container via terminal (on your host OS) you could need the container name.
Type `docker start <your-container-name-here>`. 
Use your afore mentioned superior script kiddie skills ;) and the internet and make this a cron job.

edit: use container name instead of id for docker start

**Comment by OddSquirrel** [comment]
Yes, that's the thing. Most services I use that run regular checks, like Changedetection.io or Uptime Kuma run 24/7 and the frequency of those checks is set inside the apps themselves. When idle, they use completely negligible resources, so stopping them obviously isn't even worth it and goes against the idea of scheduling. I was actually utterly dumbfounded when this container just exited after doing its job—I thought something was wrong (mind you, my skills regarding messing stuff up are honed to perfection, so that idea isn't far-fetched). 😂 It would definitely be a great feature to set some value in something like an environment variable.

My Docker instance runs inside a Debian LXC on Proxmox. With Portainer running on top, I just wasn't sure if I should fumble around directly with Docker outside of it for fear of messing stuff up for Portainer. Is that a wrong assumption?

If it really doesn't eff up the Portainer side of things, I shall merrily unleash my superior script kiddie skills unto the world. ☝

**Reply by benjaminberlin** [reply]
this works for me.
restarts every 24h (86400s)

```
# start with `docker compose up`
services:
  free-games-claimer:
    container_name: fgc # is printed in front of every output line
    image: ghcr.io/vogler/free-games-claimer # otherwise image name will be free-games-claimer-free-games-claimer
    build: .
    ports:
      # - "5900:5900" # VNC server
      - "6080:6080" # noVNC (browser-based VNC client)
    volumes:
      - /volume1/docker/freegamesclaimer/fgc:/fgc/data
    # command: bash -c "node epic-games; node gog"
    environment:
       - NOTIFY='mailto://login:password@provider.com' 
       - NOTIFY_TITLE=FREE GAMES CLAIMER
       - PG_EMAIL=***** 	#Prime Gaming Login
       - PG_PASSWORD=******	 #Prime Gaming password
       - PG_OTPKEY=***** 	#Prime Gaming OTPKEY
       - GOG_EMAIL=***** 	#GOG Store Login
       - GOG_PASSWORD=*****	 #GOG Store password
       - GOG_NEWSLETTER=0	#Do not unsubscribe from newsletter after claiming a game if 1
       - EG_EMAIL=***** 	#EPIC-GAMES Login
       - EG_PASSWORD=***** 	#EPIC-GAMES password
       - EG_OTPKEY=***** 	#EPIC-GAMES OTPKEY
       #-EG_PARENTALPIN		Epic Games Parental Controls PIN.
  restarter:
    image: docker:cli
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    command: ["/bin/sh", "-c", "while true; do sleep 86400; docker restart fgc; done"]
    restart: unless-stopped

```
