### DISCUSSION TITLE
Something went wrong, connection is closed

### DISCUSSION THREAD

**Discussion by mgrimace** [vogler/free-games-claimer#204] [Q&A] [answered]
I noticed the status of my docker container for FGC switched from `running` to `unknown`, and when I connect to the noVNC webUI it shows `Something went wrong, connection is closed` in the window.

I'm running fgc using docker compose, and it seemed to work on startup as I was able to enter captchas and follow along watching it attempt to claim games. 

Is this normal/expected behaviour since the scripts aren't running at the moment, or is there an error/issue on my end?

LOGS (from `docker logs fgc`):
```
2023-09-05 14:34:34.562 started checking epic-games
Signed in as [redacted]
Free games: [ 'https://store.epicgames.com/en-US/p/cave-story-plus' ]
  This game contains mature content recommended only for ages 18+
Current free game: Cave Story+
  Already in library! Nothing to claim.
2023-09-05 14:34:47.949 started checking prime-gaming
Signed in as [redacted]
Number of already claimed games (total): 39
Number of free unclaimed games (Prime Gaming): 0
Number of free unclaimed games (external stores): 0
2023-09-05 14:35:00.482 started checking gog
Signed in as [redacted]
Current free game: Ghost Master - https://gog.com/en/game/ghost_master
  Already in library! Nothing to claim.
Version: https://github.com/vogler/free-games-claimer/tree/b449ee4d7fd01fcc4d9054341235696fa9901a9b
Build: Tue, 05 Sep 2023 14:13:10 +0000
Xvfb display server created screen with resolution 1280x1280
Version: https://github.com/vogler/free-games-claimer/tree/b449ee4d7fd01fcc4d9054341235696fa9901a9b
```
It then continues repeating the last line about resolution over and over.

My compose:
```yaml
services:
  free-games-claimer:
    container_name: fgc
    image: ghcr.io/vogler/free-games-claimer
    environment:
      - TZ=America/Toronto
    env_file:
      - /opt/appdata/fgc/.secrets.env
    ports:
      - 6080:6080
    volumes:
      - /opt/appdata/fgc:/fgc/data
    restart: unless-stopped
    
```

Any thoughts/clarification would be appreciated, thanks!
