### ISSUE TITLE
noVNC/portal, tunnel, notifications, ARM, docker

### ISSUE THREAD

**Issue by vogler** [vogler/free-games-claimer#13]
Planning/discussion issue for the ideas that came up in #11

- [ ]  noVNC & tunnel
- [ ]  notifications
- [ ]  GitHub actions to upload to Docker hub
- [ ]  Firefox for image size / ARM
- [ ]  (Reduce the image size ([with alpine?](https://github.com/Zenika/alpine-chrome)))

**Comment by vogler** [comment]
@jackblk I added you as a collaborator and created a project board: https://github.com/vogler/free-games-claimer/projects/1

Not sure what's better, I guess having this meta issue is enough to keep an overview.

**Comment by jackblk** [comment]
@vogler I made it so it can work with Alpine in branch `docker-alpine-wip`. The chromium shipped with playwright will not work in Alpine because of [`musl`/`glibc` incompatibility](https://playwright.dev/docs/docker#alpine), so I tried using chromium build shipped with Alpine packages.

It can run, but it will be detected by captcha and I have to reset my IP for a clean one 😞 .

So for now, I save the progress in the branch, but we have to abandon this method until Playwright has better support for Alpine.

**Comment by vogler** [comment]
Maybe use
- https://github.com/klaussinani/signale for logging with colors and timer - right now the log isn't easy to read
- https://github.com/terkelg/prompts maybe for prompting the user for initial config or login data

**Comment by vogler** [comment]
Heads-up: I'll move `userDataDir` -> `data/browser`, `screenshots` -> `data/screenshots` such that there's just one directory with all user data to ignore and map into docker.

**Comment by QIN2DIM** [comment]
>  GitHub actions to upload to Docker hub

Maybe this configuration can achieve the demand. [New docker_token.](https://hub.docker.com/settings/security)

```yaml

name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
      - ".gitignore"
env:
  IMAGE_TAG: # such as vogler/free-games-claimer:alpha

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Project Init
        run: # Do some pre-processing initialization work, if not necessary, you can delete this step
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64 # linux/arm64
          push: true
          tags: ${{ env.IMAGE_TAG }}
```
