### ISSUE TITLE
Playwright Firefox missing in latest Docker Image

### ISSUE THREAD

**Issue by EthanC** [vogler/free-games-claimer#37]
After updating from Docker Image `269ebc1bbea5` to `cb43362ac418`, I am seeing the following error with a Docker Compose installation. This issue did not exist before the latest update.

`docker-compose.yml`:
```
version: "3"
services:
  free-games-claimer:
    container_name: free-games-claimer
    image: voglerr/free-games-claimer:latest
    ports:
      - 5900:5900
      - 6080:6080
    volumes:
      - /home/ethan/free-games-claimer:/fgc/data
```

Logs:
```
Xvfb display server created screen with resolution 1280x1280.
VNC is running on port 5900 (no password!).
noVNC is running on http://localhost:6080
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
browserType.launchPersistentContext: Executable doesn't exist at /root/.cache/ms-playwright/firefox-1369/firefox/firefox
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at async file:///fgc/epic-games.js:36:17 {
  name: 'Error'
}
```
