### ISSUE TITLE
Questions about setup, docker compose, config via env vars

### ISSUE THREAD

**Issue by EQUALIT-CG** [vogler/free-games-claimer#43]
Hello Everyone

I just came across this project and have run in to an issues that was bough up to me

1. I'm running this as a docker-compose i know how
2. I also have someone else look over this and pointed out two things witch i didn't see first time

I'm happy to upload my docker-compose if needed but for not i will upload a screen shot and the info needed

I'm trying to run this as a docker-compose with docker nothing new I'm doing this via my Synology NAS witch is fine
But I'm getting  error witch can be see from the Attach files
![Capture02](https://user-images.githubusercontent.com/56815873/210297508-e2c916c2-3c3c-4dd3-9d4e-5bca353cf1a1.PNG)
![Capture](https://user-images.githubusercontent.com/56815873/210297512-0444ac0c-6830-45d2-942f-e2dd3acaf935.PNG)

the issues is "npx playwright install"
The author can fix this but including this as part of it or it will fail and not run during build.

Please fix this or help me work out how to fix it I don't get how to install npx on a synology nas but besides the point should be part of the build as its a container

**Comment by vogler** [comment]
Show your docker compose config. There's some permission problem creating `/fgc/data`. It has nothing to do with npx since that's already done when building the image.

**Comment by EQUALIT-CG** [comment]
Hi @vogler

I just checked it was my mistake I was missing the fgc after the :/

This now runs fine for me Thank you that sorry for wasting your time

Last thing How does this work do i edit a config with my log in or something i just need a little how to what the ports are use for so i can tag them etc etc

Cheers

also my docker-compose looks like

```
version: '3.6'

services:
  free-games-claimer:
    container_name: fgc
    image: ghcr.io/vogler/free-games-claimer
    ports:
      - "5900:5900"              # webui...
      - "6080:6080"              # .....
    volumes:
      - /volume1/docker/test_data:/fgc/data
#      - /volume1/docker/test_data:/data
    restart: 'unless-stopped'
    environment:
      - TZ=Sydney/Australia
    user: 1061:101

networks:
  default:
    driver: bridge
```
Thanks for the help and will try and work out how to log in with my 2FA and stuff will take some time

Once i have worked out how to log in i will Close this PR

**Comment by EQUALIT-CG** [comment]
Hi guys

Does the screen shot look right / normal or I'm having issues as to why i can't open the http://localhost:6080
also not sure if its possible i saw VNC is running on port 5900 (no password!) witch is why i though maybe i can open it via the port but nope

Would be nice if can somehow plan to add a password via the environment but i have no idea if this can be done

Thanks for your support
![Uploading test.PNG…]()

**Comment by EQUALIT-CG** [comment]
![test](https://user-images.githubusercontent.com/56815873/210468566-b76dbd9d-13ee-4773-b034-d0802610ea73.PNG)

**Comment by vogler** [comment]
> what the ports are use for so i can tag them etc etc

From the readme:

> When you need to login, go to http://localhost:6080/ (you can also connect with a VNC client on port 5900)

5900 is the default port for VNC, 6080 is noVNC (browser-based VNC client).

If you don't want to enter login data, you can just set the used environment variables:
https://github.com/vogler/free-games-claimer/blob/21a2bc01a4712276c8ac1861ef493d05a127eb3f/epic-games.js#L80-L81

```
EMAIL=foo@bar.baz PASSWORD=foo docker run --rm -it -p 6080:6080 -v fgc:/fgc/data ghcr.io/vogler/free-games-claimer
```

I don't know what you're running, but you're missing firefox in the container. Maybe you're using some old image with new code. In any case, I would just delete your images and containers and run the command above.

**Comment by EQUALIT-CG** [comment]
Hi @vogler

Thank you so much i have updated my docker-compose

```

version: '3.6'

services:
  free-games-claimer:
    container_name: fgc
    image:  ghcr.io/vogler/free-games-claimer
    ports:
      - "5900:5900"                 # (client-based VNC client) 
      - "6080:6080"                 # (browser-based VNC client)
    volumes:
      - /volume1/docker/test_data:/fgc/data
    restart: 'unless-stopped'
    environment:
      - TZ=Sydney/Australia
#    user: 1061:101
    environment:
      - PUID=1061
      - PGID=101

networks:
  default:
    driver: bridge
    ```
    
    I hope my ports # look right i got it running what was wrong was my environment i should of use it like above 
    
    I'm still working on this stuff as i don't really understand it so if you can try and explain it to me in a simple term please do
    
![image](https://user-images.githubusercontent.com/56815873/210692169-2bd44bfc-fb2a-44fc-bbaa-328b3dcb5efe.png)


I did get the browser-based VNC client working :D

How do i get / log in and Claim Amazon or the other sites will that be the same as the noVNC just google and log in with that brower

its not a bad VNC i though would be same as a Proxmox VNC but aye it works Thanks so much


Pending a review from @vogler before close this ticket as i need to work out how to log in and add a VNC password

**Comment by EQUALIT-CG** [comment]
Hi @vogler

Thank you so much i have updated my docker-compose

```
version: '3.6'

services:
  free-games-claimer:
    container_name: fgc
    image:  ghcr.io/vogler/free-games-claimer
    ports:
      - "5900:5900"                 # (client-based VNC client) 
      - "6080:6080"                 # (browser-based VNC client)
    volumes:
      - /volume1/docker/test_data:/fgc/data
    restart: 'unless-stopped'
    environment:
      - TZ=Sydney/Australia
#    user: 1061:101
    environment:
      - PUID=1061
      - PGID=101

networks:
  default:
    driver: bridge
    ```
    
I hope my ports # look right i got it running what was wrong was my environment i should of use it like above 
    
I'm still working on this stuff as i don't really understand it so if you can try and explain it to me in a simple term please do

![Capture](https://user-images.githubusercontent.com/56815873/210698742-0e027234-0837-41d3-8518-f6f60b6c5975.PNG)



I did get the browser-based VNC client working :D

How do i get / log in and Claim Amazon or the other sites will that be the same as the noVNC just google and log in with that brower

its not a bad VNC i though would be same as a Proxmox VNC but aye it works Thanks so much


Pending a review from @vogler before close this ticket as i need to work out how to log in and add a VNC password
