### ISSUE TITLE
GOG Fails to Authenticate, Results in Timeout and TypeError

### ISSUE THREAD

**Issue by EthanC** [vogler/free-games-claimer#53]
As GOG is now run by default in Docker, I've found that it is failing to authenticate using credentials provided via environment variables. After an unsuccessful attempt to claim the current free game, FGC opens the login form but does not submit credentials.

https://user-images.githubusercontent.com/16727756/215296931-2339241d-c695-4672-bb7a-d458d0698ccf.mp4

Docker Compose
```yml
version: "3"
services:
  free-games-claimer:
    container_name: free-games-claimer
    image: voglerr/free-games-claimer:latest
    environment:
      WIDTH: 1280
      HEIGHT: 720
      NOTIFY: discord://XXXXX/XXXXX
      EMAIL: XXXXX
      EG_PASSWORD: XXXXX
      EG_OTPKEY: XXXXX
      PG_PASSWORD: XXXXX
      PG_OTPKEY: XXXXX
      GOG_PASSWORD: XXXXX
    ports:
      - 5900:5900
      - 6080:6080
    volumes:
      - /home/XXXXX/free-games-claimer:/fgc/data
```

Logs
```
2023-01-29 00:06:33.929 started checking gog
Signed in as ''
Current free game: CDPR Goodie Pack - https://gog.com/en/game/cdpr_goodie_pack
Unauthorized 
Unsubscribe from 'Promotions and hot deals' newsletter
locator.uncheck: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('li:has-text("Promotions and hot deals") label')
============================================================
    at file:///fgc/gog.js:121:73 {
  name: 'TimeoutError'
}
file:///fgc/gog.js:125
  if (!error.message.contains('Target closed')) // e.g. when killed by Ctrl-C
                     ^
TypeError: error.message.contains is not a function
    at file:///fgc/gog.js:125:22
Node.js v19.5.0
```
