### ISSUE TITLE
[GOG] TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by EthanC** [vogler/free-games-claimer#60]
Docker Compose
```yml
version: "3"
services:
  free-games-claimer:
    container_name: free-games-claimer
    image: voglerr/free-games-claimer:latest
    environment:
      WIDTH: 1280
      HEIGHT: 720
      NOTIFY: discord://XXXXX
      EMAIL: XXXXX
      EG_PASSWORD: XXXXX
      EG_OTPKEY: XXXXX
      PG_PASSWORD: XXXXX
      PG_OTPKEY: XXXXX
      GOG_PASSWORD: XXXXX
    ports:
      - 5900:5900
      - 6080:6080
    volumes:
      - /home/ethan/free-games-claimer:/fgc/data
```

Logs
```
2023-02-15 17:00:16.213 started checking gog
Signed in as 'Ethan'
TypeError: Cannot read properties of null (reading '1')
    at file:///fgc/gog.js:90:58
```
