### ISSUE TITLE
Question about `BROWSER_DIR` vs. volume

### ISSUE THREAD

**Issue by EQUALIT-CG** [vogler/free-games-claimer#92]
Hello @vogler 

May i please have some info on if i need some but how to add the Brower_Dir

if my docker compose looks like this 

```
version: '3.6'

services:
  free-games-claimer:
    container_name: fgc
    image:  ghcr.io/vogler/free-games-claimer
    ports:
#      - "5900:5900"                 # (client-based VNC client)
      - "6080:6080"                 # (browser-based VNC client)
    volumes:
      - /volume1/docker/games-claimer_data:/fgc/data
#    restart: on-failure:5
#    restart: 'unless-stopped'
    command: bash -c "node epic-games"
    environment:
      - TZ=Sydney/Australia
      - SHOWVMC=1
      - VNC_PASSWORD=tusmhahjtjskhhjt
      - PUID=1061
      - PGID=101
      - EG_EMAIL=example@mail.com
      - EG_PASSWORD=vb#9Q
#      - PG_EMAIL=example@mail.com
#      - PG_PASSWORD=

networks:
  default:
    driver: bridge
```
    
    
If i make an 
    
```
    Brower_Dir=Epic
    Brower_Dir=Steam
    Brower_Dir
```
    
   is the above how it works does i take it its not
   also is this where the screen shots for each store will be if i set up the Brower_Dir etc etc
   
   I just need a little help and with my volumes above in the Docker-compose i'm sure you can work it out
   
   also how would i run this non stop with out having to docker-compose up every 48 hours
   
   running this via a Synology NAS right now
